Home page fixes
modrinth/olympus pull request #650
Opened 2023-08-21 13:03 UTC by Banzobotic

Fixes underline on description tab not showing up when projects are opened from the homepage as outlined in #649. 

Also makes it so that the play or install button on cards doesn't show up if the mouse is over the corners of cards in the area removed by border radius, so it now only shows up if the mouse is over the area that is actually shown. 

closes #649

2023-08-28 19:47 UTC, CodexAdrian requested changes

2023-08-28 19:47 UTC, CodexAdrian commented on theseus_gui/src/components/ui/ProjectCard.vue
> +    <Card class="project-card button-base" @click="$router.push(`/project/${project.slug}/`)">
This should still use the router from `const router = useRouter()`, its functionally the same but we try to avoid using dollar sign syntax in theseus

2023-08-28 19:47 UTC, CodexAdrian commented on theseus_gui/src/components/ui/ProjectCard.vue
> -const router = useRouter()
Is there a reason you switched to the other syntax for this function?

2023-08-29 10:08 UTC, Banzobotic commented on theseus_gui/src/components/ui/ProjectCard.vue
> -const router = useRouter()
SearchCard used the dollar sign syntax so I changed it to be the same. Reverted now.

2023-12-12 03:46 UTC, triphora approved these changes

2024-07-04 03:13 UTC, closed without merging