Adds a "Show per page" dropdown for mods page
modrinth/olympus pull request #710
Opened 2023-09-02 07:01 UTC by cgcha

Closes #692

![image](https://github.com/modrinth/theseus/assets/20671184/77c4d952-3459-4907-8181-6a7083f20ed7)

Adds a "Show per page" dropdown similar to that in the browse menu. Defaults to 20 as previously, but maxes out to the entire modlist if the user wants all their mods on a single page. Also supports values below optional values

![image](https://github.com/modrinth/theseus/assets/20671184/1434ab2e-d837-4456-89cd-7be889331aa5)

I left a comment on the css which would push the page count to the next line, but kept it commented to keep the behavior the same as on the browse page.

2023-09-02 20:21 UTC, Prospector requested changes
The location of the dropdown just seems kinda thrown in and kinda breaks the design when it wraps to the next line. Needs some rethinking there

Also, I would show all of the options regardless of how many projects there actually are in the instance, and the option should save its state globally in my opinion. In addition to the 5, 10, 15, 20, 50, and 100, I would add a "All" option which would remove pagination.

2023-09-02 21:14 UTC, cgcha commented
>The location of the dropdown just seems kinda thrown in and kinda breaks the design when it wraps to the next line. 

I thought so too at the time but I modeled it after the browse page on the app.

![image](https://github.com/modrinth/theseus/assets/20671184/c232c297-5f12-41d7-aa69-93470769e25b)
^^ This is how it looks on the latest release, which is kind of confusing in hindsight because the website has a different behavior keeping everything in the same line:

![image](https://github.com/modrinth/theseus/assets/20671184/5e9ce6fe-1bc6-42df-b19c-20723068dd9b)

I didn't want to make a change outside of the mod page, but both the mod list search and browse search would need a change for a more consistent search card

2023-09-03 09:22 UTC, cgcha commented
![image](https://github.com/modrinth/theseus/assets/20671184/7175da26-d337-4dca-a2c5-d932bde9549d)

Some minor changes, mainly the above feedback. At this point, more feedback would be appreciated on other changes:
- "the option should save its state globally in my opinion" The current implementation saves pagination selection using a global state, but this is reset on relaunch of the program. It wouldn't be too difficult to add another setting to the rust code that would persist on relaunch, but it might also be unnecessary.
- Most of the changed could also be applied to the browse page, except removing the "all" choice so user's can't endlessly query the site. 
- I'm still not quite happy with the design, but I'm also trying to keep it in line with the browse page.

2023-09-03 09:23 UTC, cgcha commented
Also probably relevant to #716

2024-07-04 03:13 UTC, closed without merging